# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'win.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Widget(object):
    def setupUi(self, Widget):
        Widget.setObjectName("Widget")
        Widget.resize(932, 329)
        self.imgLable = QtWidgets.QLabel(Widget)
        self.imgLable.setGeometry(QtCore.QRect(60, 80, 240, 240))
        self.imgLable.setAlignment(QtCore.Qt.AlignCenter)
        self.imgLable.setObjectName("imgLable")
        self.layoutWidget = QtWidgets.QWidget(Widget)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 20, 340, 30))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lineEditPortNum = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEditPortNum.setObjectName("lineEditPortNum")
        self.horizontalLayout.addWidget(self.lineEditPortNum)
        self.btnLinkConn = QtWidgets.QPushButton(self.layoutWidget)
        self.btnLinkConn.setObjectName("btnLinkConn")
        self.horizontalLayout.addWidget(self.btnLinkConn)
        self.groupBox = QtWidgets.QGroupBox(Widget)
        self.groupBox.setGeometry(QtCore.QRect(360, 20, 361, 141))
        self.groupBox.setObjectName("groupBox")
        self.layoutWidget1 = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 20, 350, 108))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(0, -1, -1, -1)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.btnManual = QtWidgets.QPushButton(self.layoutWidget1)
        self.btnManual.setMinimumSize(QtCore.QSize(0, 0))
        self.btnManual.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.btnManual.setObjectName("btnManual")
        self.verticalLayout.addWidget(self.btnManual)
        self.btnAuto = QtWidgets.QPushButton(self.layoutWidget1)
        self.btnAuto.setMinimumSize(QtCore.QSize(0, 0))
        self.btnAuto.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.btnAuto.setObjectName("btnAuto")
        self.verticalLayout.addWidget(self.btnAuto)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.btnGoForward = QtWidgets.QPushButton(self.layoutWidget1)
        self.btnGoForward.setMinimumSize(QtCore.QSize(30, 30))
        self.btnGoForward.setMaximumSize(QtCore.QSize(30, 30))
        self.btnGoForward.setObjectName("btnGoForward")
        self.gridLayout.addWidget(self.btnGoForward, 0, 1, 1, 1)
        self.btnGoLeft = QtWidgets.QPushButton(self.layoutWidget1)
        self.btnGoLeft.setMinimumSize(QtCore.QSize(30, 30))
        self.btnGoLeft.setMaximumSize(QtCore.QSize(30, 30))
        self.btnGoLeft.setObjectName("btnGoLeft")
        self.gridLayout.addWidget(self.btnGoLeft, 1, 0, 1, 1)
        self.btnGoStop = QtWidgets.QPushButton(self.layoutWidget1)
        self.btnGoStop.setMinimumSize(QtCore.QSize(30, 30))
        self.btnGoStop.setMaximumSize(QtCore.QSize(30, 30))
        self.btnGoStop.setObjectName("btnGoStop")
        self.gridLayout.addWidget(self.btnGoStop, 1, 1, 1, 1)
        self.btnGoRight = QtWidgets.QPushButton(self.layoutWidget1)
        self.btnGoRight.setMinimumSize(QtCore.QSize(30, 30))
        self.btnGoRight.setMaximumSize(QtCore.QSize(30, 30))
        self.btnGoRight.setObjectName("btnGoRight")
        self.gridLayout.addWidget(self.btnGoRight, 1, 2, 1, 1)
        self.btnGoBack = QtWidgets.QPushButton(self.layoutWidget1)
        self.btnGoBack.setMinimumSize(QtCore.QSize(30, 30))
        self.btnGoBack.setMaximumSize(QtCore.QSize(30, 30))
        self.btnGoBack.setObjectName("btnGoBack")
        self.gridLayout.addWidget(self.btnGoBack, 2, 1, 1, 1)
        self.horizontalLayout_2.addLayout(self.gridLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setContentsMargins(0, -1, -1, -1)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.btnGoUp = QtWidgets.QPushButton(self.layoutWidget1)
        self.btnGoUp.setMinimumSize(QtCore.QSize(0, 0))
        self.btnGoUp.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.btnGoUp.setObjectName("btnGoUp")
        self.verticalLayout_2.addWidget(self.btnGoUp)
        self.btnGoDown = QtWidgets.QPushButton(self.layoutWidget1)
        self.btnGoDown.setMinimumSize(QtCore.QSize(0, 0))
        self.btnGoDown.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.btnGoDown.setObjectName("btnGoDown")
        self.verticalLayout_2.addWidget(self.btnGoDown)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.groupBox_2 = QtWidgets.QGroupBox(Widget)
        self.groupBox_2.setGeometry(QtCore.QRect(360, 170, 361, 141))
        self.groupBox_2.setObjectName("groupBox_2")
        self.layoutWidget2 = QtWidgets.QWidget(self.groupBox_2)
        self.layoutWidget2.setGeometry(QtCore.QRect(10, 10, 341, 121))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.btnModeDepthkeep = QtWidgets.QPushButton(self.layoutWidget2)
        self.btnModeDepthkeep.setMinimumSize(QtCore.QSize(60, 30))
        self.btnModeDepthkeep.setMaximumSize(QtCore.QSize(60, 30))
        self.btnModeDepthkeep.setObjectName("btnModeDepthkeep")
        self.horizontalLayout_3.addWidget(self.btnModeDepthkeep)
        self.sliderDepthNum = QtWidgets.QSlider(self.layoutWidget2)
        self.sliderDepthNum.setMinimumSize(QtCore.QSize(0, 0))
        self.sliderDepthNum.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.sliderDepthNum.setMaximum(200)
        self.sliderDepthNum.setPageStep(5)
        self.sliderDepthNum.setSliderPosition(0)
        self.sliderDepthNum.setOrientation(QtCore.Qt.Horizontal)
        self.sliderDepthNum.setTickPosition(QtWidgets.QSlider.NoTicks)
        self.sliderDepthNum.setObjectName("sliderDepthNum")
        self.horizontalLayout_3.addWidget(self.sliderDepthNum)
        self.labelDepthNum = QtWidgets.QLabel(self.layoutWidget2)
        self.labelDepthNum.setAlignment(QtCore.Qt.AlignCenter)
        self.labelDepthNum.setObjectName("labelDepthNum")
        self.horizontalLayout_3.addWidget(self.labelDepthNum)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.btnSpeedSet = QtWidgets.QPushButton(self.layoutWidget2)
        self.btnSpeedSet.setMinimumSize(QtCore.QSize(60, 30))
        self.btnSpeedSet.setMaximumSize(QtCore.QSize(60, 30))
        self.btnSpeedSet.setObjectName("btnSpeedSet")
        self.horizontalLayout_4.addWidget(self.btnSpeedSet)
        self.sliderSpeedSet = QtWidgets.QSlider(self.layoutWidget2)
        self.sliderSpeedSet.setMinimumSize(QtCore.QSize(0, 0))
        self.sliderSpeedSet.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.sliderSpeedSet.setMaximum(300)
        self.sliderSpeedSet.setOrientation(QtCore.Qt.Horizontal)
        self.sliderSpeedSet.setObjectName("sliderSpeedSet")
        self.horizontalLayout_4.addWidget(self.sliderSpeedSet)
        self.labelSpeedNum = QtWidgets.QLabel(self.layoutWidget2)
        self.labelSpeedNum.setAlignment(QtCore.Qt.AlignCenter)
        self.labelSpeedNum.setObjectName("labelSpeedNum")
        self.horizontalLayout_4.addWidget(self.labelSpeedNum)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_2.setMinimumSize(QtCore.QSize(0, 0))
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_5.addWidget(self.label_2)
        self.textBrowserDepth = QtWidgets.QTextBrowser(self.layoutWidget2)
        self.textBrowserDepth.setMinimumSize(QtCore.QSize(0, 30))
        self.textBrowserDepth.setMaximumSize(QtCore.QSize(16777215, 30))
        self.textBrowserDepth.setObjectName("textBrowserDepth")
        self.horizontalLayout_5.addWidget(self.textBrowserDepth)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_3.setMinimumSize(QtCore.QSize(0, 30))
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_5.addWidget(self.label_3)
        self.textBrowserVoltage = QtWidgets.QTextBrowser(self.layoutWidget2)
        self.textBrowserVoltage.setMinimumSize(QtCore.QSize(0, 30))
        self.textBrowserVoltage.setMaximumSize(QtCore.QSize(16777215, 30))
        self.textBrowserVoltage.setObjectName("textBrowserVoltage")
        self.horizontalLayout_5.addWidget(self.textBrowserVoltage)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.groupBox_3 = QtWidgets.QGroupBox(Widget)
        self.groupBox_3.setGeometry(QtCore.QRect(740, 20, 161, 141))
        self.groupBox_3.setObjectName("groupBox_3")
        self.layoutWidget3 = QtWidgets.QWidget(self.groupBox_3)
        self.layoutWidget3.setGeometry(QtCore.QRect(10, 20, 141, 81))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.formLayout = QtWidgets.QFormLayout(self.layoutWidget3)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label_4 = QtWidgets.QLabel(self.layoutWidget3)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.lineEditP = QtWidgets.QLineEdit(self.layoutWidget3)
        self.lineEditP.setObjectName("lineEditP")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEditP)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget3)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.lineEditI = QtWidgets.QLineEdit(self.layoutWidget3)
        self.lineEditI.setObjectName("lineEditI")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEditI)
        self.label_6 = QtWidgets.QLabel(self.layoutWidget3)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.lineEditD = QtWidgets.QLineEdit(self.layoutWidget3)
        self.lineEditD.setObjectName("lineEditD")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEditD)
        self.btnPIDsend = QtWidgets.QPushButton(self.groupBox_3)
        self.btnPIDsend.setGeometry(QtCore.QRect(10, 110, 93, 28))
        self.btnPIDsend.setObjectName("btnPIDsend")
        self.groupBox_4 = QtWidgets.QGroupBox(Widget)
        self.groupBox_4.setGeometry(QtCore.QRect(740, 170, 161, 141))
        self.groupBox_4.setObjectName("groupBox_4")
        self.layoutWidget4 = QtWidgets.QWidget(self.groupBox_4)
        self.layoutWidget4.setGeometry(QtCore.QRect(10, 20, 151, 101))
        self.layoutWidget4.setObjectName("layoutWidget4")
        self.formLayout_2 = QtWidgets.QFormLayout(self.layoutWidget4)
        self.formLayout_2.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_7 = QtWidgets.QLabel(self.layoutWidget4)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.textBrowserRoll = QtWidgets.QTextBrowser(self.layoutWidget4)
        self.textBrowserRoll.setMinimumSize(QtCore.QSize(0, 27))
        self.textBrowserRoll.setMaximumSize(QtCore.QSize(16777215, 27))
        self.textBrowserRoll.setObjectName("textBrowserRoll")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.textBrowserRoll)
        self.label_8 = QtWidgets.QLabel(self.layoutWidget4)
        self.label_8.setObjectName("label_8")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.textBrowserPitch = QtWidgets.QTextBrowser(self.layoutWidget4)
        self.textBrowserPitch.setMinimumSize(QtCore.QSize(0, 27))
        self.textBrowserPitch.setMaximumSize(QtCore.QSize(16777215, 27))
        self.textBrowserPitch.setObjectName("textBrowserPitch")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.textBrowserPitch)
        self.label_9 = QtWidgets.QLabel(self.layoutWidget4)
        self.label_9.setObjectName("label_9")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.textBrowserYaw = QtWidgets.QTextBrowser(self.layoutWidget4)
        self.textBrowserYaw.setMinimumSize(QtCore.QSize(0, 27))
        self.textBrowserYaw.setMaximumSize(QtCore.QSize(16777215, 27))
        self.textBrowserYaw.setObjectName("textBrowserYaw")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.textBrowserYaw)

        self.retranslateUi(Widget)
        QtCore.QMetaObject.connectSlotsByName(Widget)

    def retranslateUi(self, Widget):
        _translate = QtCore.QCoreApplication.translate
        Widget.setWindowTitle(_translate("Widget", "Widget"))
        self.imgLable.setText(_translate("Widget", "视频显示区"))
        self.label.setText(_translate("Widget", "端口号："))
        self.btnLinkConn.setText(_translate("Widget", "开启TCP连接"))
        self.groupBox.setTitle(_translate("Widget", "机器人姿态控制"))
        self.btnManual.setText(_translate("Widget", "手控"))
        self.btnAuto.setText(_translate("Widget", "自动"))
        self.btnGoForward.setText(_translate("Widget", "前"))
        self.btnGoLeft.setText(_translate("Widget", "左"))
        self.btnGoStop.setText(_translate("Widget", "停"))
        self.btnGoRight.setText(_translate("Widget", "右"))
        self.btnGoBack.setText(_translate("Widget", "后"))
        self.btnGoUp.setText(_translate("Widget", "上浮"))
        self.btnGoDown.setText(_translate("Widget", "下潜"))
        self.groupBox_2.setTitle(_translate("Widget", "功能"))
        self.btnModeDepthkeep.setText(_translate("Widget", "定深"))
        self.labelDepthNum.setText(_translate("Widget", "***cm"))
        self.btnSpeedSet.setText(_translate("Widget", "调速"))
        self.labelSpeedNum.setText(_translate("Widget", "*****"))
        self.label_2.setText(_translate("Widget", "深度："))
        self.label_3.setText(_translate("Widget", "电压："))
        self.groupBox_3.setTitle(_translate("Widget", "PID调参"))
        self.label_4.setText(_translate("Widget", "P"))
        self.label_5.setText(_translate("Widget", "I"))
        self.label_6.setText(_translate("Widget", "D"))
        self.btnPIDsend.setText(_translate("Widget", "发送"))
        self.groupBox_4.setTitle(_translate("Widget", "姿态显示"))
        self.label_7.setText(_translate("Widget", "ROLL："))
        self.label_8.setText(_translate("Widget", "PITCH："))
        self.label_9.setText(_translate("Widget", "YAW："))
